// <auto-generated />
using BookStore.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookStore.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231025213950_AddedFields")]
    partial class AddedFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookStore.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryDescrition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KeyWords")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("BookStore.Models.ChildrenBook", b =>
                {
                    b.HasBaseType("BookStore.Models.Category");

                    b.Property<int>("PurposeAge")
                        .HasColumnType("int");

                    b.ToTable("ChildrenBooks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 3,
                            CategoryDescrition = "Child desc",
                            IconUrl = "",
                            KeyWords = "Fairy tale",
                            Name = "Children's literature",
                            PurposeAge = 10
                        });
                });

            modelBuilder.Entity("BookStore.Models.DictionaryBook", b =>
                {
                    b.HasBaseType("BookStore.Models.Category");

                    b.Property<string>("IntoLanguage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NativeLanguage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("DictionaryBooks", (string)null);
                });

            modelBuilder.Entity("BookStore.Models.FictionBook", b =>
                {
                    b.HasBaseType("BookStore.Models.Category");

                    b.Property<string>("LiteraryFormat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("FictionBook", (string)null);
                });

            modelBuilder.Entity("BookStore.Models.HistoryBook", b =>
                {
                    b.HasBaseType("BookStore.Models.Category");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("HistoryBooks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryDescrition = "HISTORY desc",
                            IconUrl = "",
                            KeyWords = "Ukraine history",
                            Name = "History",
                            Period = "19"
                        },
                        new
                        {
                            Id = 2,
                            CategoryDescrition = "HISTORY desc",
                            IconUrl = "",
                            KeyWords = "USA history",
                            Name = "History",
                            Period = "19"
                        });
                });

            modelBuilder.Entity("BookStore.Models.ScientificBook", b =>
                {
                    b.HasBaseType("BookStore.Models.Category");

                    b.Property<string>("KnowledgeBranch")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("ScientificBook", (string)null);
                });

            modelBuilder.Entity("BookStore.Models.ChildrenBook", b =>
                {
                    b.HasOne("BookStore.Models.Category", null)
                        .WithOne()
                        .HasForeignKey("BookStore.Models.ChildrenBook", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookStore.Models.DictionaryBook", b =>
                {
                    b.HasOne("BookStore.Models.Category", null)
                        .WithOne()
                        .HasForeignKey("BookStore.Models.DictionaryBook", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookStore.Models.FictionBook", b =>
                {
                    b.HasOne("BookStore.Models.Category", null)
                        .WithOne()
                        .HasForeignKey("BookStore.Models.FictionBook", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookStore.Models.HistoryBook", b =>
                {
                    b.HasOne("BookStore.Models.Category", null)
                        .WithOne()
                        .HasForeignKey("BookStore.Models.HistoryBook", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookStore.Models.ScientificBook", b =>
                {
                    b.HasOne("BookStore.Models.Category", null)
                        .WithOne()
                        .HasForeignKey("BookStore.Models.ScientificBook", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
